CREATE TABLE MARCA (
	MARCA_ID INTEGER(10) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE MODELO (
	MODELO_ID INTEGER(10) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE AVIAO (
	NUM_SERIE INTEGER(3) PRIMARY KEY,
	MARCA INTEGER(10) REFERENCES TIPO_AVIAO(MARCA_ID),
	MODELO INTEGER(10) REFERENCES TIPO_AVIAO(MODELO_ID) 
);

CREATE TABLE TIPO_AVIAO (
	MARCA INTEGER(10) REFERENCES MARCA(MARCA_ID),
	MODELO INTEGER(10) REFERENCES MODELO(MODELO_ID),
	VELOCIDADE_MAX INTEGER(10) NOT NULL,
	CAPACIDADE_DEPOSITO INTEGER(10) NOT NULL,
	CARGA_MAX INTEGER(10) NOT NULL,
	HORAS_VOO_MIN TIME NOT NULL,
	TOTAL_LUGARES INTEGER(10) NOT NULL,
	CONSTRAINT PK_TIPO_AVIAO PRIMARY KEY (MARCA, MODELO)
);

CREATE TABLE CLASSE (
	CLASSE_ID INTEGER(10) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE CLASSE_TIPO_AVIAO (
	MARCA INTEGER(10) REFERENCES TIPO_AVIAO(MARCA_ID),
	MODELO INTEGER(10) REFERENCES TIPO_AVIAO(MODELO_ID),
	CLASSE INTEGER(10) REFERENCES CLASSE(CLASSE_ID),
	CONSTRAINT PK_CLASSE_TIPO_AVIAO PRIMARY KEY (MARCA, MODELO, CLASSE)
);

CREATE TABLE LUGAR (
	NUM_FILA INTEGER(10),
	LETRA CHAR(1),
	MARCA INTEGER(10) REFERENCES CLASSE_TIPO_AVIAO(MARCA_ID),
	MODELO INTEGER(10) REFERENCES CLASSE_TIPO_AVIAO(MODELO_ID),
	CLASSE INTEGER(10) REFERENCES CLASSE_TIPO_AVIAO(CLASSE_ID),
	CONSTRAINT PK_LUGAR PRIMARY KEY (NUM_FILA, LETRA, MARCA, MODELO, CLASSE)
);

CREATE TABLE CATEGORIA_TRIP (
	CATEGORIA_TRIP_ID INTEGER(10) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SALARIO_MENSAL FLOAT(10) NOT NULL
);

CREATE TABLE TRIPULANTE (
	TRIPULANTE_ID INTEGER(10) PRIMARY KEY,
	CATEGORIA INTEGER(10) REFERENCES CATEGORIA_TRIP(CATEGORIA_TRIP_ID)
);

CREATE TABLE HORAS_VOO (
	PILOTO_ID INTEGER(10),
	MARCA INTEGER(10) REFERENCES TIPO_AVIAO(MARCA_ID),
	MODELO INTEGER(10) REFERENCES TIPO_AVIAO(MODELO_ID),
	HORAS_VOO TIME NOT NULL,
	CONSTRAINT PK_HORAS_VOO PRIMARY KEY (PILOTO_ID, MARCA, MODELO)
);

CREATE TABLE VIAGEM_PLANEADA (
	VIAGEM_PLANEADA_ID INTEGER(10) PRIMARY KEY,
	VOO_REGULAR INTEGER(10) REFERENCES VOO_REGULAR(VOO_REGULAR_ID),
	DATA_PLANEADA_PARTIDA DATE NOT NULL,
	DATA_PLANEADA_CHEGADA DATE NOT NULL,
);

CREATE TABLE VIAGEM_REALIZADA (
	VIAGEM_REALIZADA_ID INTEGER(10) PRIMARY KEY REFERENCES VIAGEM_PLANEADA(VIAGEM_PLANEADA_ID),
	DATA_REALIZADA_PARTIDA DATE NOT NULL,
	DATA_REALIZADA_CHEGADA DATE NOT NULL,
);

CREATE TABLE TRIPULANTE_CABINE (
	VIAGEM_REALIZADA INTEGER(10) REFERENCES VIAGEM_REALIZADA(VIAGEM_REALIZADA_ID),
	TRIPULANTE INTEGER(10) REFERENCES TRIPULANTE(TRIPULANTE_ID),
	FUNCAO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TRIP_CABINE PRIMARY KEY (VIAGEM_REALIZADA, TRIPULANTE)
);

CREATE TABLE TRIPULANTE_TECNICO (
	VIAGEM_REALIZADA INTEGER(10) REFERENCES VIAGEM_REALIZADA(VIAGEM_REALIZADA_ID),
	TRIPULANTE INTEGER(10) REFERENCES TRIPULANTE(TRIPULANTE_ID),
	FUNCAO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_TRIP_TECNICO PRIMARY KEY (VIAGEM_REALIZADA, TRIPULANTE)
);

CREATE TABLE PASSAGEIRO (
	PASSAGEIRO_ID INTEGER(10) PRIMARY KEY,
	PRIMEIRO_NOME VARCHAR(50) NOT NULL,
	ULTIMO_NOME VARCHAR(50) NOT NULL,
	TIPO_DOCUMENTO VARCHAR(50) NOT NULL,
	NUM_DOCUMENTO INTEGER(9) NOT NULL
);

CREATE TABLE RESERVA (
	RESERVA_ID INTEGER(10) PRIMARY KEY,
	PASSAGEIRO INTEGER(10) REFERENCES PASSAGEIRO(PASSAGEIRO_ID),
	VOO_REGULAR INTEGER(10) REFERENCES PRECO(VOO_REGULAR_ID),
	CLASSE INTEGER(10) REFERENCES PRECO(CLASSE_ID),
	NUM_FILA_LUGAR INTEGER(3),
	LETRA_LUGAR CHAR(1) 
);



