CREATE TABLE LATITUDE (
	LATITUDE_ID INTEGER(10) PRIMARY KEY,
	GRAUS INTEGER(3) NOT NULL,
	MINUTOS INTEGER(2) NOT NULL,
	SEGUNDOS INTEGER(2) NOT NULL,
	ORIENTACAO CHAR(1) NOT NULL
);

CREATE TABLE LONGITUDE (
	LONGITUDE_ID INTEGER(10) PRIMARY KEY,
	GRAUS INTEGER(3) NOT NULL,
	MINUTOS INTEGER(2) NOT NULL,
	SEGUNDOS INTEGER(2) NOT NULL,
	ORIENTACAO CHAR(1) NOT NULL
);

CREATE TABLE PAIS (
	PAIS_ID INTEGER(3) PRIMARY KEY,
	NOME VARCHAR(50)
);

CREATE TABLE CIDADE (
	CIDADE_ID INTEGER(10) PRIMARY KEY,
	PAIS_ID INTEGER(3) REFERENCES PAIS(PAIS_ID),
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE AEROPORTO (
	IATA_ID CHAR(3) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	CIDADE_ID INTEGER(10) REFERENCES CIDADE(CIDADE_ID),
	LONGITUDE_ID INTEGER(10) REFERENCES LONGITUDE(LONGITUDE_ID),
	LATITUDE_ID INTEGER(10) REFERENCES LATITUDE(LATITUDE_ID)
);

CREATE TABLE ROTA (
	ROTA_ID INTEGER(10) PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE CATEGORIA_VOO (
	CAT_VOO_ID INTEGER(10) PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL
);

CREATE TABLE VOO (
	VOO_ID INTEGER(10) PRIMARY KEY,
	DISTANCIA INTEGER(5) NOT NULL,
	DURACAO TIME NOT NULL,
	AEROPORTO_ORIGEM CHAR(3) REFERENCES AEROPORTO(IATA_ID),
	AEROPORTO_DESTINO CHAR(3) REFERENCES AEROPORTO(IATA_ID),
	CAT_VOO_ID INTEGER(10) REFERENCES CATEGORIA_VOO(CAT_VOO_ID)
);

CREATE TABLE VOO_ROTA(
	ROTA_ID INTEGER(10) REFERENCES ROTA(ROTA_ID),
	VOO_ID INTEGER(10) REFERENCES VOO(VOO_ID),
	CONSTRAINT PK_VOO_ROTA PRIMARY KEY (ROTA_ID, VOO_ID)
);

CREATE TABLE PLANO(
	PLANO_ID INTEGER(10) PRIMARY KEY,
	DESCRICAO VARCHAR(50) NOT NULL,
	DATA_INICIO DATE NOT NULL,
	DATA_FIM DATE NOT NULL
);

CREATE TABLE VOO_REGULAR(
	VOO_REGULAR_ID INTEGER(10) PRIMARY KEY,
	PLANO_ID INTEGER(10) REFERENCES PLANO(PLANO_ID),
	VOO_ID INTEGER(10) REFERENCES VOO(VOO_ID),
	AVIAO INTEGER(3) REFERENCES AVIAO(NUM_SERIE),
	DIA_DA_SEMANA INTEGER(1) NOT NULL,
	HORARIO_PARTIDA TIME NOT NULL
);

CREATE TABLE PRECO(
	VOO_REGULAR_ID INTEGER(10) REFERENCES VOO_REGULAR(VOO_REGULAR_ID),
	CLASSE_ID INTEGER(4) REFERENCES CLASSE(CLASSE_ID),
	PRECO FLOAT(10) NOT NULL,
	CONSTRAINT PK_PRECO PRIMARY KEY (VOO_REGULAR_ID, CLASSE_ID)
);

CREATE TABLE BONUS(
	CAT_VOO_ID INTEGER(10) REFERENCES CATEGORIA_VOO(CAT_VOO_ID),
	CATEGORIA_TRIP_ID INTEGER(10) REFERENCES CATEGORIA_TRIP(CATEGORIA_TRIP_ID),
	BONUS FLOAT(10) NOT NULL,
	CONSTRAINT PK_BONUS PRIMARY KEY (CAT_VOO_ID, CATEGORIA_TRIP_ID)
);