-- ### TESTAR FUNCTION 4 ###
-- ### FIM TESTE FUNCTION 4 ###
-- ### TESTAR FUNCTION 6 ###
-- ### FIM TESTE FUNCTION 6 ###
-- ### TESTAR PROCEDURE 8 ###
-- ### FIM TESTE PROCEDURE 8 ###


-- ### TESTAR PROCEDURE 9 ###
DECLARE
  DATA_INICIO_PERIODO DATE;
  DATA_FINAL_PERIODO DATE;
BEGIN
  DATA_INICIO_PERIODO := TO_DATE('2016/12/01', 'YYYY/MM/DD');
  DATA_FINAL_PERIODO := TO_DATE('2016/12/31', 'YYYY/MM/DD');
  
  PC_CRIAR_VIAGENS(DATA_INICIO_PERIODO, DATA_FINAL_PERIODO);
END;
/
-- ### FIM TESTE PROCEDURE 9 ###

-- ### INICIO TESTE AO TRIGGER 10 ###
	INSERT INTO TRIPULANTE_TECNICO VALUES (1, 1, 'PILOTO'); -- INSERIR COMISSARIO (FALSE)
	INSERT INTO TRIPULANTE_TECNICO VALUES (1, 13, 'CO-PILOTO'); -- INSERIR CO-PILOTO (TRUE)
	INSERT INTO TRIPULANTE_TECNICO VALUES (1, 14, 'PILOTO'); -- INSERIR PILOTO S/ MIN HORAS (FALSE)
	INSERT INTO TRIPULANTE_TECNICO VALUES (1, 16, 'PILOTO'); -- INSERIR PILOTO C/ MIN HORAS (TRUE)

	-- SO APARECE O CO-PILOTO #13 E O PILOTO #16
	SELECT * FROM TRIPULANTE_TECNICO WHERE VIAGEM_PLANEADA = 1;
-- ### FIM DO TESTE AO TRIGGER 10 ###

-- ### TESTAR O TRIGGER 11 PARA TRIPULANTES TÉCNICOS ###

INSERT INTO VOO VALUES (9, 1000, 120, 'VAR', 'LIS', 2); -- NEW
INSERT INTO VOO_REGULAR VALUES (14, 1, 8, 'F04', 3, '20:00'); --NEW
INSERT INTO VOO_REGULAR VALUES (15, 1, 9, 'F04', 3, '18:30'); --NEW
INSERT INTO VIAGEM_PLANEADA VALUES (8, 14, TO_DATE('2016/12/13 20:00','YYYY/MM/DD HH24:MI'), TO_DATE('2016/12/13 21:00','YYYY/MM/DD HH24:MI')); -- NEW
INSERT INTO VIAGEM_PLANEADA VALUES (9, 15, TO_DATE('2016/12/13 18:30','YYYY/MM/DD HH24:MI'), TO_DATE('2016/12/13 20:30','YYYY/MM/DD HH24:MI')); -- NEW

SELECT *
FROM VIAGEM_PLANEADA VP, TRIPULANTE_TECNICO TP, TRIPULANTE T, VOO_REGULAR VR, VOO V
WHERE TP.VIAGEM_PLANEADA = VP.VIAGEM_PLANEADA_ID AND TP.TRIPULANTE = T.TRIPULANTE_ID
AND VP.VOO_REGULAR = VR.VOO_REGULAR_ID AND VR.VOO_ID = V.VOO_ID
AND T.TRIPULANTE_ID = 13 AND TRUNC(VP.DATA_PLANEADA_PARTIDA) = TO_DATE('2016/12/13', 'YYYY/MM/DD');

INSERT INTO TRIPULANTE_TECNICO VALUES (8, 13, 'PILOTO');
INSERT INTO TRIPULANTE_TECNICO VALUES (9, 13, 'PILOTO');

DELETE FROM TRIPULANTE_TECNICO
WHERE VIAGEM_PLANEADA BETWEEN 8 AND 9
AND TRIPULANTE = 13;

-- ### FIM DO TESTE AO TRIGGER ###